### ISSUE TITLE
Cast JSON string to object when calling MeasurementJSON.get() function

### ISSUE THREAD

**Issue by lorenzoPrimi** [TheTorProject/ooni-wui#2] opened 2016-08-16 08:15 UTC
Hi, 
when updating ooni-wui in NetProbe the iOS app, I had to change the way to inject json from

```
NSString* MeasurementJSON = [NSString stringWithFormat:@"\n var MeasurementJSON = {  \n"
                             "get: function() {  \n"
                             "return "
                             "'%@';"
                             "   } \n"
                             "}", content];
```

To

```
NSString* MeasurementJSON = [NSString stringWithFormat:@"\n var MeasurementJSON = {  \n"
                             "get: function() {  \n"
                             "return "
                             "%@;"
                             "   } \n"
                             "}", content];
```

to make it work again.
Unfortunately in the Android app something broke with the new wui and I don't have so much control to the injected json, maybe @hellais could help me identify the problem.

Android code:

```
    WebView wv = (WebView) myScrollView.findViewById(R.id.webview);
    wv.getSettings().setJavaScriptEnabled(true);
    String jsonContent = LogUtils.readLogFile(c, jsonfile);
    wv.addJavascriptInterface(new InjectedJSON(jsonContent), "MeasurementJSON");
    wv.loadUrl("file:///android_asset/html/webui/index.html");

public static class InjectedJSON {
    private String jsonData;

    public InjectedJSON(String json) {
        jsonData = json;
    }

    @JavascriptInterface
    public String get() {
        return jsonData;
    }
}
```

**Comment by hellais** [comment] 2016-08-25 08:00
Oh, yes I see what is the issue here. Basically we expect the `get()` function to return an object and not a string (https://github.com/TheTorProject/ooni-wui/blob/master/src/app/components/measurement/measurement.factory.js#L7).
In iOS this is possible, but android doesn't allow you to inject an object directly so we need to change the behaviour.

The fix to this would be to call `get()` and run the result through a `JSON.parse()` to convert it to an object.

I can't seem to find history of it working otherwise in older versions, but it may be due to the fact that the code was moved from one repo to another.

**Comment by lorenzoPrimi** [comment] 2016-08-26 10:45
Alright, I understand, so there will be a fix in this repo soon?
I wont touch anything in the netprobe-android for now.

**Comment by hellais** [comment] 2016-08-26 15:09
Pushed a fix for this. You should be good to go now.

**Comment by lorenzoPrimi** [comment] 2016-09-10 19:26
@hellais  Could this be the problem why now doesn't work in iOS?

**Comment by hellais** [comment] 2016-09-10 21:58
In the iOS version you should return a string in the javascript code.

```
NSString* MeasurementJSON = [NSString stringWithFormat:@"\n var MeasurementJSON = {  \n"
                             "get: function() {  \n"
                             "return "
                             "'%@';"
                             "   } \n"
                             "}", content];
```

Is that not what you are doing?

**Comment by lorenzoPrimi** [comment] 2016-09-11 09:05
No, now it is 

NSString\* MeasurementJSON = [NSString stringWithFormat:@"\n var MeasurementJSON = {  \n"
                             "get: function() {  \n"
                             "return "
                             "%@;"
                             "   } \n"
                             "}", content];

And it doesn't show any result. 
But even with your version I can only see the result page of tcp connect and dns injection tests.  (and ndt) Not Web connectivity and http invalid request line.
Any hint?

**Comment by hellais** [comment] 2016-09-12 10:49
@lorenzoPrimi yeah, you need to return a string instead of an object on iOS (this is because in iOS you can inject objects into javascript, but you can't do the same with Android, so the cross platform solution is to always use strings).

It's very strange that you would only see a result page for tcp_connect and dns injection tests. Do you have some way of extracting error messages from the webkit view? If so it would be useful to have the console output of the webkit view.

**Comment by lorenzoPrimi** [comment] 2016-09-12 11:13
Here are the .js of the two tests. Try it yourself building the mobile.html page.
Btw, I fixed the iOS app injecting a string instead of object.

[web_connectivity.js.txt](https://github.com/TheTorProject/ooni-wui/files/467155/web_connectivity.js.txt)
[http_invalid_request_line.js.txt](https://github.com/TheTorProject/ooni-wui/files/467156/http_invalid_request_line.js.txt)

**Comment by hellais** [comment] 2016-09-12 11:20
For the web_connectivity test the issue is that the `'` chars are not being escaped in the JSON document.

You will probably need to do something like:

`content = [content stringByReplacingOccurrencesOfString:@"'" withString:@"\'"];`

**Comment by lorenzoPrimi** [comment] 2016-09-12 11:28
good guess, but still doesn't work
[web_connectivity.js.txt](https://github.com/TheTorProject/ooni-wui/files/467177/web_connectivity.js.txt)

**Comment by lorenzoPrimi** [comment] 2016-09-16 08:46
@hellais any other guess or solution to fix this?

**Comment by hellais** [comment] 2016-09-16 13:00
So I looked a bit more into this and it seems like the issue is that for multiple entry JSON fields we need to present an intermediate view to select which specific entry (and at what index) you need to present. When that is selected you can then redirect to the page that displays the web connectivity test view.

I will try to write this up in a branch on netprobe-ios.

**Comment by hellais** [comment] 2016-09-16 14:49
So further debugging shows that the MeasurementJSON is actually malformed.

If I print it out I get:

```
2016-09-16 16:48:26.697 NetProbe[41291:2852581] 
 var MeasurementJSON = {  
get: function() {  
return '(null)';   } 
};
```

**Comment by hellais** [comment] 2016-09-16 14:51
Protip: If you need to debug the WebKit views you need to do this from Safari.

To enable debugging in Safari, open it go to Preferences -> Advanced -> Show Develop menu in menubar.

Then fire up the app and when the webview is loaded you will see under the Develop tab of the Safari app on your computer a simulator item that contains the name of the app. There you will be able to see the console and the inspector.

In order to trigger console.log messages and such you will have to reload it.

To make the reload work though I had to change the way the page is loaded to:

```
[self.webView loadHTMLString:htmlData baseURL: [NSURL fileURLWithPath:pathToHtml]];
```

**Comment by hellais** [comment] 2016-09-16 15:04
Ignore my comment  about null being returned. That was due to me having messed up some of the segue's.

I do however see that the JSON returned is malformed and I get some parsing errors with it.

```
SyntaxError: JSON Parse error: Unterminated string — mobile.bundle.js:36645
```

**Comment by hellais** [comment] 2016-09-16 15:31
Ok, pushed a fix for this on the netprobe-ios branch fix/viewresults.

I believe this issue can now be closed since it's not a problem with ooni-wui.

**Closed as completed** 2016-09-17 11:33 UTC
